[build]
builder = "NIXPACKS"
buildCommand = "npm install -g pnpm && pnpm install --frozen-lockfile && PORT=3000 BASE_PATH=/ pnpm --filter @workspace/zakpubg build && pnpm --filter @workspace/api-server build"

[deploy]
preDeployCommand = "pnpm --filter @workspace/db run push"
startCommand = "node artifacts/api-server/dist/index.mjs"
healthcheckPath = "/api/healthz"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "ZakPubgSkin"
